// components/product/ProductCard.vue
<template>
  <article class="group flex h-full flex-col overflow-hidden rounded-xl border border-border bg-card shadow-sm transition-all duration-300 hover:-translate-y-1 hover:border-gold-200 hover:shadow-premium-lg">
    <div class="relative">
      <NuxtLink
        :to="productUrl"
        class="flex aspect-square w-full items-center justify-center overflow-hidden border-b border-border bg-white p-4 sm:p-5"
      >
        <NuxtImg
          v-if="productImage"
          :src="productImage"
          :alt="product.title"
          class="h-full w-full object-contain transition-transform duration-500 group-hover:scale-105"
          :class="product.inStock === false ? 'opacity-60 grayscale' : ''"
          loading="lazy"
          format="webp"
          quality="85"
        />
        <span v-else class="text-xs font-medium text-muted-foreground/75">Visuel indisponible</span>
      </NuxtLink>

      <span
        v-if="product.inStock === false"
        class="absolute left-3 top-3 rounded-full bg-foreground/85 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-white backdrop-blur-sm"
      >
        Rupture
      </span>

      <button
        type="button"
        :aria-label="isFavorite ? 'Retirer des favoris' : 'Ajouter aux favoris'"
        :aria-pressed="isFavorite"
        :disabled="!canToggleFavorite"
        class="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-md border border-border bg-white/95 text-muted-foreground transition-colors hover:text-foreground disabled:cursor-not-allowed disabled:opacity-45"
        :class="isFavorite ? 'text-gold-700' : ''"
        @click.prevent="toggleFavorite"
      >
        <Heart class="h-4 w-4" :class="isFavorite ? 'fill-current' : ''" :stroke-width="1.75" />
      </button>
    </div>

    <div class="flex flex-1 flex-col p-3 sm:p-4">
      <p v-if="categoryName" class="mb-2 line-clamp-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
        {{ categoryName }}
      </p>
      <NuxtLink :to="productUrl">
        <h3 class="line-clamp-2 min-h-[2.5rem] text-sm font-semibold leading-5 text-foreground transition-colors group-hover:text-gold-800 sm:text-base">
          {{ product.title }}
        </h3>
      </NuxtLink>
      <p v-if="product.subtitle" class="mt-1 line-clamp-1 text-xs text-muted-foreground">
        {{ product.subtitle }}
      </p>

      <div v-if="product.inStock === true" class="mt-3 inline-flex items-center gap-1.5 text-[11px] font-medium text-emerald-700">
        <span class="h-1.5 w-1.5 rounded-full bg-emerald-500"></span>
        Disponible
      </div>

      <div class="mt-auto pt-4">
        <p v-if="hasKnownPrice" class="font-display text-lg font-semibold text-foreground sm:text-xl">
          {{ cartStore.formatPrice(product.price as number) }}
        </p>
        <p v-else class="text-xs font-medium text-muted-foreground">
          Prix non communiqué
        </p>

        <button
          v-if="canAddToCart"
          type="button"
          :aria-label="`Ajouter ${product.title} au panier`"
          class="mt-3 inline-flex h-10 w-full items-center justify-center gap-2 rounded-md bg-accent px-3 text-sm font-semibold text-accent-foreground shadow-sm transition-all hover:bg-accent/90 hover:shadow-md"
          @click="addToCart"
        >
          <ShoppingBag class="h-4 w-4" :stroke-width="1.75" />
          Ajouter
        </button>
        <NuxtLink
          v-else
          :to="productUrl"
          class="mt-3 inline-flex h-10 w-full items-center justify-center gap-1 rounded-md border border-border text-sm font-semibold text-foreground transition-colors hover:bg-muted"
        >
          Voir le produit
          <ChevronRight class="h-4 w-4" :stroke-width="1.75" />
        </NuxtLink>
      </div>
    </div>
  </article>
</template>

<script setup lang="ts">
import { ChevronRight, Heart, ShoppingBag } from 'lucide-vue-next'
import { useCartStore } from '~/stores/cart'
import { useFavoritesStore } from '~/stores/favorites'

interface ProductProp {
  id: string
  title: string
  handle?: string
  subtitle?: string
  price?: number
  thumbnail?: string
  images?: string[]
  category?: string | { name: string; handle: string }
  inStock?: boolean
}

const props = defineProps<{
  product: ProductProp
  delay?: number
}>()

const cartStore = useCartStore()
const favoritesStore = useFavoritesStore()
const toast = useToast()

const productUrl = computed(() => `/produit/${props.product.handle || props.product.id}`)
const productImage = computed(() => props.product.thumbnail || props.product.images?.[0] || '')
const categoryName = computed(() => {
  if (!props.product.category) return ''
  return typeof props.product.category === 'string' ? props.product.category : props.product.category.name
})
const isFavorite = computed(() => favoritesStore.isFavorite(props.product.id))
const hasKnownPrice = computed(() => typeof props.product.price === 'number' && Number.isFinite(props.product.price))
const canAddToCart = computed(() => props.product.inStock === true && hasKnownPrice.value)
const canToggleFavorite = computed(() => isFavorite.value || canAddToCart.value)

async function toggleFavorite() {
  if (isFavorite.value) {
    await favoritesStore.removeFromFavorites(props.product.id)
    return
  }
  if (!canAddToCart.value || !hasKnownPrice.value) return

  await favoritesStore.toggleFavorite({
    id: props.product.id,
    title: props.product.title,
    handle: props.product.handle || props.product.id,
    price: props.product.price as number,
    thumbnail: productImage.value,
    images: props.product.images || [],
    category: categoryName.value,
    categoryHandle: '',
    inStock: true,
  })
}

function addToCart() {
  if (!canAddToCart.value || !hasKnownPrice.value) return

  cartStore.addItem({
    productId: props.product.id,
    title: props.product.title,
    price: props.product.price as number,
    thumbnail: productImage.value,
    category: categoryName.value,
  })
  toast.add({
    title: 'Ajouté au panier',
    description: props.product.title,
    color: 'black',
    timeout: 2500,
  })
}
</script>

// components/shop/product-card.tsx
'use client'

import Link from 'next/link'
import Image from 'next/image'
import { Heart, Plus, ShoppingBag } from 'lucide-react'
import { toast } from 'sonner'
import { cn } from '@/lib/utils'
import type { Product } from '@/lib/types'
import { useCart } from '@/stores/cart'
import { useFavorites } from '@/stores/favorites'

export function ProductCard({ product }: { product: Product }) {
  const addItem = useCart((s) => s.addItem)
  const format = useCart((s) => s.format)
  const toggleFav = useFavorites((s) => s.toggle)
  const isFav = useFavorites((s) => s.items.some((i) => i.productId === product.id))

  const href = `/produit/${product.slug || product.id}`
  const image = product.thumbnail || product.images?.[0] || ''
  const hasPrice = typeof product.price === 'number' && Number.isFinite(product.price)
  // Products with variants need a choice on the detail page ("Voir" link) before adding.
  const canBuy = product.inStock === true && hasPrice && !product.variants?.length

  function add() {
    if (!canBuy) return
    addItem({
      productId: product.id,
      title: product.title,
      price: product.price as number,
      thumbnail: image,
      category: product.category,
    })
    toast.success('Ajouté au panier', { description: product.title })
  }

  function fav() {
    if (!hasPrice) return
    toggleFav({
      productId: product.id,
      title: product.title,
      price: product.price as number,
      thumbnail: image,
      category: product.category,
    })
  }

  return (
    <article className="group flex h-full flex-col overflow-hidden rounded-2xl border border-border bg-card transition-all duration-300 hover:-translate-y-1 hover:shadow-soft">
      <div className="relative">
        <Link href={href} className="block aspect-square overflow-hidden bg-secondary/40">
          {image ? (
            <Image
              src={image}
              alt={product.title}
              width={480}
              height={480}
              className={cn(
                'h-full w-full object-cover transition-transform duration-500 group-hover:scale-105',
                product.inStock === false && 'opacity-60 grayscale',
              )}
            />
          ) : (
            <div className="flex h-full items-center justify-center text-muted-foreground">
              <ShoppingBag className="h-8 w-8" strokeWidth={1.25} />
            </div>
          )}
        </Link>

        {product.inStock === false && (
          <span className="absolute left-3 top-3 rounded-full bg-foreground/85 px-2.5 py-1 text-[11px] font-semibold uppercase tracking-wide text-background">
            Rupture
          </span>
        )}

        <button
          type="button"
          aria-label={isFav ? 'Retirer des favoris' : 'Ajouter aux favoris'}
          aria-pressed={isFav}
          onClick={fav}
          className="absolute right-3 top-3 flex h-9 w-9 items-center justify-center rounded-full border border-border bg-card/90 text-muted-foreground backdrop-blur transition-colors hover:text-foreground"
        >
          <Heart className={cn('h-4 w-4', isFav && 'fill-accent text-accent')} strokeWidth={1.75} />
        </button>
      </div>

      <div className="flex flex-1 flex-col p-4">
        {product.category && (
          <p className="mb-1 line-clamp-1 text-[11px] font-medium uppercase tracking-wide text-muted-foreground">
            {product.category}
          </p>
        )}
        <Link href={href} className="font-medium leading-snug transition-colors hover:text-primary">
          <h3 className="line-clamp-2 min-h-[2.5rem] text-sm">{product.title}</h3>
        </Link>

        <div className="mt-auto flex items-end justify-between gap-2 pt-4">
          {hasPrice ? (
            <span className="font-display text-lg font-bold">{format(product.price as number)}</span>
          ) : (
            <span className="text-xs font-medium text-muted-foreground">Prix sur demande</span>
          )}

          {canBuy ? (
            <button
              type="button"
              aria-label={`Ajouter ${product.title} au panier`}
              onClick={add}
              className="flex h-9 w-9 items-center justify-center rounded-full bg-accent text-accent-foreground transition-transform hover:scale-105 active:scale-95"
            >
              <Plus className="h-4 w-4" strokeWidth={2.25} />
            </button>
          ) : (
            <Link
              href={href}
              className="text-xs font-semibold text-primary hover:underline"
            >
              Voir
            </Link>
          )}
        </div>
      </div>
    </article>
  )
}
