// pages/403.vue
<template>
  <div class="min-h-screen bg-background flex items-center justify-center px-4">
    <div class="text-center">
      <div class="w-24 h-24 mx-auto mb-6 bg-red-500/10 rounded-full flex items-center justify-center">
        <Icon name="lucide:shield-x" class="w-12 h-12 text-red-500" />
      </div>
      
      <h1 class="text-4xl font-bold text-foreground mb-2">403</h1>
      <h2 class="text-xl font-semibold text-muted-foreground/90 mb-4">Accès refusé</h2>
      <p class="text-muted-foreground mb-8 max-w-md mx-auto">
        Vous n'avez pas les permissions nécessaires pour accéder à cette page.
      </p>
      
      <div class="flex flex-col sm:flex-row gap-4 justify-center">
        <UButton 
          to="/" 
          color="primary"
          size="lg"
        >
          Retour à l'accueil
        </UButton>
        <UButton 
          @click="goBack" 
          color="gray"
          variant="outline"
          size="lg"
        >
          Page précédente
        </UButton>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
definePageMeta({
  layout: false
})

const router = useRouter()

const goBack = () => {
  router.back()
}

useHead({
  title: 'Accès refusé - Dounia Market'
})
</script>

// app/(shop)/403/page.tsx
import type { Metadata } from 'next'
import Link from 'next/link'
import { ShieldAlert } from 'lucide-react'
import { Button } from '@/components/ui/button'

export const metadata: Metadata = {
  title: 'Accès refusé - Dounia Market',
  description: "Vous n'avez pas les droits nécessaires pour accéder à cette page.",
}

export default function ForbiddenPage() {
  return (
    <div className="container-page flex min-h-[70vh] flex-col items-center justify-center py-16 text-center">
      <span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-destructive/10 text-destructive">
        <ShieldAlert className="h-8 w-8" strokeWidth={1.75} />
      </span>
      <p className="mt-6 font-display text-sm font-semibold uppercase tracking-wide text-muted-foreground">
        Erreur 403
      </p>
      <h1 className="mt-2 font-display text-3xl font-bold tracking-tight sm:text-4xl">Accès refusé</h1>
      <p className="mt-3 max-w-md text-muted-foreground">
        Vous n'avez pas les autorisations nécessaires pour consulter cette page.
      </p>
      <div className="mt-8 flex flex-col gap-3 sm:flex-row">
        <Button asChild>
          <Link href="/">Retour à l'accueil</Link>
        </Button>
        <Button asChild variant="outline">
          <Link href="/compte">Mon compte</Link>
        </Button>
      </div>
    </div>
  )
}
