// pages/a-propos.vue
<template>
  <div class="min-h-screen bg-background">
    <!-- Hero -->
    <section class="relative overflow-hidden border-b border-border/70 py-16 sm:py-24">
      <div class="container-main text-center">
        <div class="mx-auto mb-6 inline-flex items-center gap-2 rounded-full border border-gold-200 bg-gold-50 px-4 py-1.5 text-xs font-bold uppercase tracking-widest text-gold-700">
          <Heart class="h-4 w-4" />
          Notre histoire
        </div>
        <h1 class="heading-hero mx-auto max-w-4xl text-foreground">
          Vous commandez ici.<br/>
          <span class="text-gold-700">Nous livrons là-bas.</span>
        </h1>
        <p class="mx-auto mt-7 max-w-2xl text-lg leading-relaxed text-muted-foreground">
          Dounia Market relie la diaspora tchadienne à ceux qui comptent, restés au pays. Vous faites vos courses en ligne depuis l'étranger ; nous nous chargeons de livrer votre famille à N'Djamena.
        </p>
      </div>
    </section>

    <!-- La Mission -->
    <section class="py-24 sm:py-32">
      <div class="container-main">
        <div class="grid grid-cols-1 gap-16 md:grid-cols-2 md:gap-24">
          <div class="reveal-up">
            <h2 class="heading-section text-3xl sm:text-4xl">Plus qu'une boutique, <br/>un lien familial.</h2>
            <p class="mt-6 text-lg font-medium leading-relaxed text-muted-foreground">
              Nous savons à quel point il est important de soutenir sa famille restée au pays. Souvent, envoyer de l'argent ne suffit pas : il faut s'assurer que les besoins essentiels sont couverts.
              <br/><br/>
              C'est pourquoi nous avons créé Dounia Market. Vous choisissez les produits de qualité, et notre équipe sur place s'occupe de tout le reste, jusqu'à la remise en main propre.
            </p>
          </div>

          <div class="space-y-10 reveal-up">
            <div class="group rounded-2xl border border-border bg-card p-6 shadow-sm transition-all hover:border-gold-200 hover:shadow-premium">
              <div class="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-gold-50 text-gold-700">
                <Store class="h-6 w-6" :stroke-width="1.5" />
              </div>
              <h3 class="mb-2 text-xl font-bold text-foreground">Produits locaux & de qualité</h3>
              <p class="text-base font-medium leading-relaxed text-muted-foreground">
                Notre catalogue est constitué de produits stockés à N'Djamena, prêts à être livrés. Pas d'attente internationale interminable.
              </p>
            </div>
            
            <div class="group rounded-2xl border border-border bg-card p-6 shadow-sm transition-all hover:border-gold-200 hover:shadow-premium">
              <div class="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-gold-50 text-gold-700">
                <ShieldCheck class="h-6 w-6" :stroke-width="1.5" />
              </div>
              <h3 class="mb-2 text-xl font-bold text-foreground">Livraison 100% sécurisée</h3>
              <p class="text-base font-medium leading-relaxed text-muted-foreground">
                Nos livreurs connaissent la ville. Nous remettons la commande en main propre et vous envoyons une preuve de livraison.
              </p>
            </div>
            
            <div class="group rounded-2xl border border-border bg-card p-6 shadow-sm transition-all hover:border-gold-200 hover:shadow-premium">
              <div class="mb-4 flex h-12 w-12 items-center justify-center rounded-xl bg-gold-50 text-gold-700">
                <HeartHandshake class="h-6 w-6" :stroke-width="1.5" />
              </div>
              <h3 class="mb-2 text-xl font-bold text-foreground">Service client dédié</h3>
              <p class="text-base font-medium leading-relaxed text-muted-foreground">
                Une équipe à votre écoute pour vous accompagner et résoudre le moindre imprévu.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <!-- CTA Final -->
    <section class="py-24 pt-0">
      <div class="container-main max-w-4xl text-center">
        <div class="overflow-hidden rounded-3xl border border-border bg-card p-10 shadow-premium sm:p-16">
          <h2 class="heading-section mb-6 text-3xl sm:text-4xl">Un geste pour ceux qui comptent</h2>
          <p class="mx-auto mb-10 max-w-xl text-lg leading-relaxed text-muted-foreground">
            Parcourez notre sélection — essentiels, épicerie, et bien d'autres choses du quotidien — à faire livrer directement à N'Djamena.
          </p>
          <div class="flex flex-col items-center justify-center gap-4 sm:flex-row">
            <NuxtLink to="/catalogue" class="btn-primary">
              <span>Explorer le catalogue</span>
            </NuxtLink>
            <NuxtLink to="/comment-ca-marche" class="btn-outline">
              Voir comment ça marche
            </NuxtLink>
          </div>
        </div>
      </div>
    </section>
  </div>
</template>

<script setup lang="ts">
import { Heart, Store, ShieldCheck, HeartHandshake } from 'lucide-vue-next'

useSeoMeta({
  title: 'À propos de nous | Dounia Market Tchad',
  description: 'Dounia Market est le pont entre la diaspora tchadienne et N\'Djamena. Découvrez notre mission : vous permettre de faire les courses pour vos proches au pays.',
  ogTitle: 'À propos | Dounia Market Tchad',
  ogDescription: 'Le service e-commerce dédié à la diaspora tchadienne pour soutenir leurs proches à N\'Djamena.',
})
</script>

// dounia-market-redesign/app/(shop)/a-propos/page.tsx
import type { Metadata } from 'next'
import Link from 'next/link'
import Image from 'next/image'
import { Heart, ShieldCheck, Truck } from 'lucide-react'
import { Button } from '@/components/ui/button'

export const metadata: Metadata = {
  title: 'À propos - Dounia Market Tchad',
  description:
    "Dounia Market relie la diaspora tchadienne à ses proches en livrant des produits essentiels à N'Djamena.",
}

const VALUES = [
  { icon: Heart, title: 'Proximité', desc: 'Nous rapprochons les familles séparées par la distance.' },
  { icon: ShieldCheck, title: 'Confiance', desc: 'Des commandes claires et un suivi à chaque étape.' },
  { icon: Truck, title: 'Fiabilité', desc: "Une livraison soignée à N'Djamena, dans les zones desservies." },
]

export default function AProposPage() {
  return (
    <div className="container-page py-12 md:py-16">
      <div className="mx-auto max-w-3xl">
        <p className="text-xs font-semibold uppercase tracking-wide text-primary">Notre histoire</p>
        <h1 className="mt-2 font-display text-4xl font-bold tracking-tight">À propos de Dounia Market</h1>
        <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
          Dounia Market est né d'une idée simple : permettre à la diaspora tchadienne d'offrir le nécessaire
          à ses proches restés au pays, sans contrainte de distance.
        </p>

        <div className="mt-8 overflow-hidden rounded-2xl border border-border shadow-soft">
          <Image
            src="/images/home/hero-marketplace.jpg"
            alt="Marché local à N'Djamena"
            width={1200}
            height={600}
            className="h-auto w-full object-cover"
          />
        </div>

        <div className="mt-10 space-y-4 text-base leading-relaxed text-foreground/90">
          <p>
            Beaucoup de Tchadiens vivent et travaillent à l'étranger tout en gardant un lien fort avec leur
            famille. Envoyer de l'argent ne suffit pas toujours : il faut souvent connaître les bons commerces,
            organiser les achats et la livraison. Dounia Market simplifie tout cela.
          </p>
          <p>
            Vous choisissez les produits depuis notre catalogue, vous réglez en ligne dans votre devise, et nous
            nous chargeons de préparer la commande et de la remettre à vos proches à N'Djamena. Vous suivez chaque
            étape jusqu'à la livraison.
          </p>
          <p>
            Notre ambition est de devenir le pont de confiance entre la diaspora et le Tchad, en élargissant
            progressivement notre catalogue et nos zones de livraison.
          </p>
        </div>

        <div className="mt-12 grid gap-5 sm:grid-cols-3">
          {VALUES.map(({ icon: Icon, title, desc }) => (
            <div key={title} className="rounded-2xl border border-border bg-card p-5">
              <span className="flex h-11 w-11 items-center justify-center rounded-xl bg-primary/10 text-primary">
                <Icon className="h-5 w-5" strokeWidth={1.75} />
              </span>
              <h2 className="mt-4 font-display text-base font-semibold">{title}</h2>
              <p className="mt-1 text-sm text-muted-foreground">{desc}</p>
            </div>
          ))}
        </div>

        <div className="mt-12 flex flex-col gap-3 rounded-2xl bg-secondary/50 p-6 sm:flex-row sm:items-center sm:justify-between">
          <div>
            <h2 className="font-display text-lg font-semibold">Envie de faire plaisir à vos proches ?</h2>
            <p className="mt-1 text-sm text-muted-foreground">Parcourez notre catalogue dès maintenant.</p>
          </div>
          <Button asChild className="shrink-0">
            <Link href="/catalogue">Voir le catalogue</Link>
          </Button>
        </div>
      </div>
    </div>
  )
}
