// pages/suivi.vue
<template>
  <div class="min-h-screen bg-background pt-24 pb-24">
    <section class="relative py-14 sm:py-16 overflow-hidden">
      <div class="absolute inset-0 z-0 opacity-[0.03]" style="background-image: radial-gradient(circle at center, #000 1px, transparent 1px); background-size: 24px 24px;"></div>
      
      <div class="max-w-3xl mx-auto px-6 relative z-10 text-center">
        <div 
          v-motion :initial="{ opacity: 0, y: 10 }" :enter="{ opacity: 1, y: 0 }"
          class="w-14 h-14 mx-auto rounded-lg bg-card border border-border shadow-sm flex items-center justify-center mb-6 relative"
        >
          <MapPin class="w-7 h-7 text-foreground relative z-10" />
        </div>
        <h1 
          v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0, transition: { delay: 100 } }"
          class="text-3xl sm:text-4xl font-bold text-foreground tracking-tight mb-4"
        >
          Suivi de commande
        </h1>
        <p 
          v-motion :initial="{ opacity: 0, y: 20 }" :enter="{ opacity: 1, y: 0, transition: { delay: 200 } }"
          class="text-base sm:text-lg text-muted-foreground max-w-xl mx-auto leading-relaxed"
        >
          Consultez l'avancement de votre commande livrée localement à N'Djamena.
        </p>
      </div>
    </section>

    <div class="max-w-2xl mx-auto px-6 pb-20">
      <div class="bg-card rounded-lg border border-border shadow-sm p-6 sm:p-8 mb-6">
        <form @submit.prevent="trackOrder" class="relative">
          <label class="block text-sm font-medium text-foreground mb-3">Référence de commande</label>
          <div class="flex flex-col sm:flex-row gap-4">
            <div class="relative flex-grow">
              <Package class="absolute left-6 top-1/2 -translate-y-1/2 w-5 h-5 text-muted-foreground/60" />
              <input 
                v-model="orderNumber" 
                type="text" 
                placeholder="Saisissez votre référence"
                class="block w-full pl-12 pr-4 h-12 bg-background border border-input rounded-md text-sm text-foreground focus:outline-none focus:ring-1 focus:ring-ring focus:border-brand transition-all shadow-sm"
                required 
              />
            </div>
            <button type="submit" :disabled="isSearching" class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-brand text-brand-foreground hover:bg-brand/90 h-12 px-8 sm:w-auto w-full shrink-0">
              <Loader v-if="isSearching" class="w-4 h-4 animate-spin mr-2" />
              <Search v-else class="w-4 h-4 mr-2" />
              <span v-if="!isSearching">Rechercher</span>
              <span v-else>Recherche...</span>
            </button>
          </div>
        </form>
        <div class="mt-5 flex items-start gap-3 rounded-md bg-muted/50 p-4 text-sm text-muted-foreground">
          <ShieldCheck class="mt-0.5 h-4 w-4 shrink-0 text-foreground" />
          <p>Saisissez uniquement la référence de commande. Ne partagez pas ici de nom, adresse ou numéro de téléphone.</p>
        </div>
      </div>

      <!-- Order Found Result -->
      <Transition
        enter-active-class="transition-all duration-500 ease-out"
        enter-from-class="opacity-0 translate-y-8"
        enter-to-class="opacity-100 translate-y-0"
      >
        <div v-if="order" class="bg-card rounded-lg border border-border shadow-sm overflow-hidden relative">
           
          <div class="p-6 sm:p-8 border-b border-border/50 relative z-10 flex flex-col sm:flex-row justify-between items-start gap-6 bg-muted/30">
            <div>
              <p class="text-xs font-medium text-muted-foreground mb-1">Commande</p>
              <p class="text-2xl font-bold text-foreground tracking-tight">{{ order.reference }}</p>
            </div>
            
            <span class="px-3 py-1 rounded-md text-[10px] font-bold uppercase tracking-widest border"
              :class="order.fulfillment_status === 'delivered' ? 'bg-green-500/10 text-green-600 border-green-500/20' : 'bg-brand/10 text-brand border-brand/20'"
            >
              {{ order.fulfillment_status === 'delivered' ? 'Livrée' : 'En cours' }}
            </span>
          </div>
          
          <div class="p-6 sm:p-8">
             <div class="flex items-center justify-between mb-6">
                <span class="text-xs font-medium text-muted-foreground">Avancement</span>
                <span class="text-sm font-bold text-foreground">{{ Math.round(completedPercent) }}%</span>
             </div>
             
             <div class="h-1.5 bg-muted rounded-full mb-10 overflow-hidden shadow-inner border border-border/50">
                <div 
                  class="h-full bg-brand rounded-full transition-all duration-1000 ease-out relative"
                  :style="{ width: `${completedPercent}%` }"
                >
                </div>
             </div>

            <div class="relative max-w-lg mx-auto">
              <div class="absolute left-6 top-4 bottom-4 w-px bg-border" />
              
              <div v-for="(step, i) in order.timeline" :key="i" class="relative pl-14 pb-8 last:pb-0 group">
                <div 
                  class="absolute left-0 w-12 h-12 rounded-full flex items-center justify-center transition-all duration-500 border border-background shadow-sm"
                  :class="step.completed 
                    ? 'bg-brand text-brand-foreground'
                    : 'bg-muted text-muted-foreground'"
                >
                  <component :is="timelineIcons[step.key] || Package" class="w-4 h-4" />
                </div>
                
                <div class="pt-1.5">
                  <p class="text-base font-bold tracking-tight" :class="step.completed ? 'text-foreground' : 'text-muted-foreground'">
                    {{ step.title }}
                  </p>
                  <p v-if="step.detail" class="text-sm font-medium leading-relaxed mt-1" :class="step.completed ? 'text-muted-foreground' : 'text-muted-foreground/40'">
                    {{ step.detail }}
                  </p>
                  <p class="text-[10px] font-bold uppercase tracking-widest mt-2" :class="step.completed ? 'text-muted-foreground' : 'text-muted-foreground/40'">
                    {{ step.date || 'En attente' }}
                  </p>
                </div>
              </div>
            </div>
          </div>
          
          <!-- Actions -->
          <div class="p-6 sm:p-8 border-t border-border flex justify-center bg-muted/10">
            <NuxtLink to="/contact" class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 border border-input bg-background hover:bg-accent hover:text-accent-foreground h-11 px-8">
              <MessageCircle class="w-4 h-4 mr-2" />
              Contacter le support
            </NuxtLink>
          </div>
        </div>
      </Transition>

      <!-- Not Found Error State -->
      <Transition
        enter-active-class="transition-all duration-300"
        enter-from-class="opacity-0 scale-95"
        enter-to-class="opacity-100 scale-100"
      >
        <div v-if="notFound" class="bg-card rounded-lg border border-destructive/20 p-8 sm:p-12 text-center shadow-sm">
          <div class="w-16 h-16 rounded-full bg-destructive/10 flex items-center justify-center mx-auto mb-6">
            <SearchX class="w-8 h-8 text-destructive" />
          </div>
           <h3 class="text-xl font-bold text-foreground mb-2">Référence introuvable</h3>
           <p class="text-muted-foreground mb-8 max-w-sm mx-auto">
             Aucune commande ne correspond à cette référence. Vérifiez la saisie ou contactez l'assistance.
           </p>
          <NuxtLink to="/contact" class="inline-flex items-center justify-center rounded-md text-sm font-medium ring-offset-background transition-colors focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 disabled:pointer-events-none disabled:opacity-50 bg-brand text-brand-foreground hover:bg-brand/90 h-11 px-8">
            <MessageCircle class="w-4 h-4 mr-2" />
            Contacter l'assistance
          </NuxtLink>
        </div>
      </Transition>
    </div>
  </div>
</template>

<script setup lang="ts">
import { MapPin, Search, Check, SearchX, Package, MessageCircle, Loader, Clock, ShieldCheck } from 'lucide-vue-next'
import type { PublicOrderStatus } from '~/types'

const route = useRoute()
const config = useRuntimeConfig()

const orderNumber = ref((route.query.ref as string) || '')
const order = ref<PublicOrderStatus | null>(null)
const notFound = ref(false)
const isSearching = ref(false)
const timelineIcons = {
  payment: Check,
  processing: Package,
  shipped: Clock,
  delivered: Check,
}

const completedPercent = computed(() => {
  if (!order.value?.timeline) return 0
  const completed = order.value.timeline.filter(step => step.completed).length
  return (completed / order.value.timeline.length) * 100
})

const trackOrder = async () => {
  if (!orderNumber.value.trim()) return
  order.value = null
  notFound.value = false
  isSearching.value = true

  await new Promise(resolve => setTimeout(resolve, 800))

  try {
    const data = await $fetch<PublicOrderStatus>(
      `${config.public.apiUrl}/orders/status/${encodeURIComponent(orderNumber.value.trim())}`
    )
    order.value = data
  } catch (e: any) {
    notFound.value = true
    if (e?.status !== 404) console.error('Tracking error:', e)
  } finally {
    isSearching.value = false
  }
}

onMounted(() => {
  if (orderNumber.value) trackOrder()
})

useHead({ title: 'Suivi de commande | Dounia Market' })
</script>

<style scoped>
@keyframes wiggle {
  0%, 100% { transform: translateX(0); }
  50% { transform: translateX(200%); }
}
</style>

// dounia-market-redesign/app/(shop)/suivi/page.tsx
'use client'

import { useState } from 'react'
import {
  AlertCircle,
  CheckCircle2,
  Circle,
  Loader2,
  MapPin,
  Package,
  PackageSearch,
  Truck,
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { cn } from '@/lib/utils'

type OrderStatus = Record<string, any> | null

const STEPS = [
  { key: 'pending', label: 'Commande reçue', icon: Package },
  { key: 'preparing', label: 'En préparation', icon: PackageSearch },
  { key: 'shipping', label: 'En cours de livraison', icon: Truck },
  { key: 'delivered', label: 'Livrée', icon: CheckCircle2 },
]

// Map various backend status strings to a step index.
function statusToIndex(status?: string): number {
  const s = (status || '').toLowerCase()
  if (/(deliver|livr|complet|termin)/.test(s)) return 3
  if (/(ship|transit|cours|route|en_livraison|out_for)/.test(s)) return 2
  if (/(prepar|process|en_cours|confirm|paid|pay)/.test(s)) return 1
  return 0
}

function statusLabel(status?: string): string {
  const s = (status || '').toLowerCase()
  if (/(deliver|livr)/.test(s)) return 'Livrée'
  if (/(ship|transit|cours|route|out_for)/.test(s)) return 'En cours de livraison'
  if (/(prepar|process)/.test(s)) return 'En préparation'
  if (/(cancel|annul)/.test(s)) return 'Annulée'
  if (/(pending|recu|reçu|paid|pay|confirm)/.test(s)) return 'Commande reçue'
  return status || 'Statut inconnu'
}

export default function SuiviPage() {
  const [reference, setReference] = useState('')
  const [state, setState] = useState<'idle' | 'loading' | 'found' | 'notfound' | 'error'>('idle')
  const [order, setOrder] = useState<OrderStatus>(null)

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault()
    const ref = reference.trim()
    if (!ref) return
    setState('loading')
    setOrder(null)
    try {
      const res = await fetch(`/api/order-status/${encodeURIComponent(ref)}`)
      if (res.status === 404) {
        setState('notfound')
        return
      }
      if (!res.ok) {
        setState('error')
        return
      }
      const data = await res.json().catch(() => null)
      setOrder(data && (data.order ?? data))
      setState('found')
    } catch {
      setState('error')
    }
  }

  const rawStatus: string | undefined = order?.status ?? order?.state ?? order?.fulfillment_status
  const currentIndex = statusToIndex(rawStatus)
  const items: any[] = Array.isArray(order?.items)
    ? order.items
    : Array.isArray(order?.line_items)
      ? order.line_items
      : []
  const recipient = order?.recipient ?? order?.recipient_name ?? order?.customer_name
  const city = order?.city ?? order?.address?.city ?? order?.recipient_city

  return (
    <div className="container-page py-10 md:py-14">
      <div className="mx-auto max-w-2xl">
        <header className="text-center">
          <h1 className="font-display text-3xl font-bold tracking-tight sm:text-4xl">Suivre une commande</h1>
          <p className="mt-2 text-sm text-muted-foreground">
            Saisissez votre référence de commande pour connaître son statut en temps réel.
          </p>
        </header>

        <form onSubmit={handleSubmit} className="mt-8 rounded-2xl border border-border bg-card p-5 shadow-soft">
          <Label htmlFor="reference" className="text-sm font-medium">
            Référence de commande
          </Label>
          <div className="mt-2 flex flex-col gap-3 sm:flex-row">
            <Input
              id="reference"
              value={reference}
              onChange={(e) => setReference(e.target.value)}
              placeholder="Ex : DM-2026-00123"
              autoComplete="off"
              className="h-11"
            />
            <Button type="submit" disabled={state === 'loading' || !reference.trim()} className="h-11 sm:px-6">
              {state === 'loading' ? (
                <>
                  <Loader2 className="h-4 w-4 animate-spin" strokeWidth={1.75} />
                  Recherche
                </>
              ) : (
                'Suivre'
              )}
            </Button>
          </div>
        </form>

        <div className="mt-6">
          {state === 'notfound' && (
            <div className="flex items-start gap-3 rounded-2xl border border-border bg-card p-5">
              <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-destructive" strokeWidth={1.75} />
              <div>
                <p className="font-semibold">Commande introuvable</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  Vérifiez la référence saisie. Elle figure dans votre e-mail de confirmation.
                </p>
              </div>
            </div>
          )}

          {state === 'error' && (
            <div className="flex items-start gap-3 rounded-2xl border border-border bg-card p-5">
              <AlertCircle className="mt-0.5 h-5 w-5 shrink-0 text-destructive" strokeWidth={1.75} />
              <div>
                <p className="font-semibold">Une erreur est survenue</p>
                <p className="mt-1 text-sm text-muted-foreground">
                  Impossible de récupérer le statut pour le moment. Réessayez dans un instant.
                </p>
              </div>
            </div>
          )}

          {state === 'found' && order && (
            <div className="space-y-5">
              <div className="rounded-2xl border border-border bg-card p-6 shadow-soft">
                <div className="flex flex-wrap items-center justify-between gap-2">
                  <div>
                    <p className="text-xs font-medium uppercase tracking-wide text-muted-foreground">
                      Référence
                    </p>
                    <p className="font-display text-lg font-semibold">
                      {order.reference ?? order.id ?? reference.trim()}
                    </p>
                  </div>
                  <span className="inline-flex items-center gap-2 rounded-full bg-secondary px-3 py-1.5 text-sm font-semibold text-secondary-foreground">
                    <span className="h-2 w-2 rounded-full bg-accent" />
                    {statusLabel(rawStatus)}
                  </span>
                </div>

                {(recipient || city) && (
                  <div className="mt-5 flex items-start gap-3 border-t border-border pt-5 text-sm">
                    <MapPin className="mt-0.5 h-4 w-4 shrink-0 text-primary" strokeWidth={1.75} />
                    <p className="text-muted-foreground">
                      {recipient && <span className="font-medium text-foreground">{recipient}</span>}
                      {recipient && city && ' - '}
                      {city}
                    </p>
                  </div>
                )}

                {/* Timeline */}
                <ol className="mt-6 space-y-0">
                  {STEPS.map((step, i) => {
                    const done = i < currentIndex
                    const active = i === currentIndex
                    const Icon = step.icon
                    return (
                      <li key={step.key} className="relative flex gap-4 pb-6 last:pb-0">
                        {i < STEPS.length - 1 && (
                          <span
                            className={cn(
                              'absolute left-[15px] top-8 h-[calc(100%-1rem)] w-0.5',
                              done ? 'bg-primary' : 'bg-border',
                            )}
                          />
                        )}
                        <span
                          className={cn(
                            'relative z-10 flex h-8 w-8 shrink-0 items-center justify-center rounded-full border',
                            done && 'border-primary bg-primary text-primary-foreground',
                            active && 'border-accent bg-accent text-accent-foreground',
                            !done && !active && 'border-border bg-card text-muted-foreground',
                          )}
                        >
                          {done ? (
                            <CheckCircle2 className="h-4 w-4" strokeWidth={2} />
                          ) : active ? (
                            <Icon className="h-4 w-4" strokeWidth={1.75} />
                          ) : (
                            <Circle className="h-3 w-3" strokeWidth={1.75} />
                          )}
                        </span>
                        <div className="pt-1">
                          <p
                            className={cn(
                              'text-sm font-medium',
                              active ? 'text-foreground' : done ? 'text-foreground' : 'text-muted-foreground',
                            )}
                          >
                            {step.label}
                          </p>
                        </div>
                      </li>
                    )
                  })}
                </ol>
              </div>

              {items.length > 0 && (
                <div className="rounded-2xl border border-border bg-card p-6">
                  <h2 className="font-display text-base font-semibold">Articles</h2>
                  <ul className="mt-4 divide-y divide-border">
                    {items.map((it, idx) => (
                      <li key={idx} className="flex items-center justify-between gap-3 py-3 text-sm">
                        <span className="font-medium">{it.title ?? it.name ?? it.product_title ?? 'Article'}</span>
                        {(it.quantity ?? it.qty) != null && (
                          <span className="shrink-0 text-muted-foreground">x{it.quantity ?? it.qty}</span>
                        )}
                      </li>
                    ))}
                  </ul>
                </div>
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
